// SPDX-License-Identifier: UNLICENSED

// Author: TrejGun
// Email: trejgun@gemunion.io
// Website: https://gemunion.io/

pragma solidity ^0.8.13;

import "@openzeppelin/contracts/utils/Address.sol";
import "@openzeppelin/contracts/finance/PaymentSplitter.sol";
import "@openzeppelin/contracts/token/ERC721/utils/ERC721Holder.sol";
import "@openzeppelin/contracts/token/ERC1155/utils/ERC1155Holder.sol";

import "@gemunion/contracts-erc20/contracts/extensions/ERC1363Receiver.sol";

import "../utils/constants.sol";
import "./ExchangeCore.sol";
import "./ExchangeGrade.sol";
import "./ExchangeClaim.sol";

/**
 * @dev This contract serves as the core Exchange contract in our ecosystem
 *      It is designed to manage various types of token exchanges with different mechanics,
 *      enabling the transfer of multiple tokens in a single transaction and facilitating payment with multiple tokens.
 *      The contract allows to withdraw profit generated by the system and to share it among multiple parties.
 */
contract Exchange is
  ExchangeCore,
  ExchangeGrade,
  ExchangeClaim,
  PaymentSplitter,
  ERC721Holder,
  ERC1155Holder,
  ERC1363Receiver
{
  using Address for address;

  constructor(
    string memory name,
    address[] memory payees,
    uint256[] memory shares
  ) SignatureValidator(name) PaymentSplitter(payees, shares) {
    address account = _msgSender();
    _setupRole(DEFAULT_ADMIN_ROLE, account);
    _setupRole(MINTER_ROLE, account);
    _setupRole(PAUSER_ROLE, account);
    _setupRole(METADATA_ROLE, account);
  }

  /**
   * @dev Pauses the contract.
   */
  function pause() public onlyRole(PAUSER_ROLE) {
    _pause();
  }

  /**
   * @dev Unpauses the contract.
   */
  function unpause() public onlyRole(PAUSER_ROLE) {
    _unpause();
  }

  /**
   * @dev See {IERC165-supportsInterface}.
   */
  function supportsInterface(
    bytes4 interfaceId
  ) public view virtual override(AccessControl, ERC1155Receiver) returns (bool) {
    return super.supportsInterface(interfaceId);
  }
}
